language: node_js
node_js:
  - 'node'
  - '8'
install:
  - npm install -g codecov
  - npm install
script:
  - ./node_modules/.bin/nyc npm test
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - codecov
