language: node_js
node_js:
  - 'node'
  - '8'
install:
  - npm install -g codecov
  - npm install
script:
  - node ./node_modules/nyc/bin/nyc --reporter=text-lcov ./node_modules/mocha/bin/mocha > coverage.lcov
  - codecov
